spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/parking_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Server port (default 8080)
server.port=8080
